### PR TITLE
Favicon change

### PR DESCRIPTION
**Pull request by s-paquette**
Replace default favicon with IDC-logo favicon (32x32 transparent PNG)

### CODE REVIEW

**Comment by fedorov** [comment]
Could you also update all of the icons in that folder? My guess those are for website shortcuts for mobile?

**Comment by s-paquette** [comment]
Oh that's probably true. Sure thing.

**Comment by fedorov** [comment]
I used this as an opportunity to check connecting this repo to our ZenHub workspace ... interesting, but not quite what I wanted ... Should review this later at some point.

I guess the most useful thing is that we can connect PRs/issues from other repos under the org to Epics in the management repo (which is what I did), may help organize things.

**Comment by s-paquette** [comment]
Added the rest - @fedorov how's that look?

**Comment by s-paquette** [comment]
Note, we might want to adjust this because if someone is using a dark theme a transparent favicon may not look so great--I have an appt to run to shortly but when I can get back I'll look at some options eg. with a pale drop-shadow/glow which would disappear on a light theme and let it show up on a dark one, and you can see if you'd prefer that. (Or I can just put them on a white background, of course.)

**Comment by fedorov** [comment]
Great, thank you! I will create an issue for the dark theme, so we don't forget.

**Comment by fedorov** [comment]
@s-paquette don't know why, but the favicon update does not show up (tested in Chrome Incognito)

image

**Comment by s-paquette** [comment]
Possibly a cache issue--does empty cache hard reload work?

**Comment by fedorov** [comment]
I tested in incognito for that specific reason - I thought I should not have any cookies/caching, no?

**Comment by fedorov** [comment]
anyway, this is not a high priority issue, I was just hoping it can be resolved quickly. If not, can address later.

**Comment by fedorov** [comment]
No idea what was going on, I probably misunderstand how favicon caching and chrome incognito work together, but I just noticed it is working now! All set!

**Pull request merged**
